# Generated by Django 5.0.3 on 2024-03-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0001_create_users_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="verified_at",
            new_name="confirmed_at",
        ),
    ]
