# Generated by Django 5.0.3 on 2024-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0002_rename_verified_at_user_confirmed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Determines when the account was verified.",
                null=True,
                verbose_name="confirmed at",
            ),
        ),
    ]
