# Generated by Django 5.0.3 on 2024-03-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0003_alter_user_confirmed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_identity_uid",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Google Identity UID",
            ),
        ),
    ]
