# Generated by Django 5.0.3 on 2024-03-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0006_schedule_scheduleavailability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduleavailability",
            name="user",
        ),
    ]
