# Generated by Django 5.0.3 on 2024-03-26 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0007_remove_scheduleavailability_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=150)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="active status"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(default=30, help_text="duration in minutes."),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("one_on_one", "One-on-One"),
                            ("group", "Group"),
                            ("collective", "Collective"),
                            ("gathering", "Gathering"),
                        ],
                        help_text="\n            ONE_ON_ONE - One host with one invitee\n            GROUP - One host with group of invitees\n            COLLECTIVE - More than one host with one invitee\n            GATHERING - Multiple host with multiple invitees\n        ",
                        max_length=20,
                        verbose_name="event type",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_events",
                        to="calyvim.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("user_id", "slug"), name="unique_user_slug"
            ),
        ),
    ]
