# Generated by Django 5.0.3 on 2024-03-26 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0008_event_event_unique_user_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventHost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="confirmed attendance"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to="calyvim.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_hosts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_hosts",
            },
        ),
        migrations.AddConstraint(
            model_name="eventhost",
            constraint=models.UniqueConstraint(
                fields=("event_id", "user_id"), name="unqiue_event_user"
            ),
        ),
    ]
